insert into public.kelimeler
  (kelime, anlam, ornek_cumle, kategori, slug)
values
  ('ağzı kulaklarına varmak', 'Çok sevinmek.', 'Haberi alınca ağzı kulaklarına vardı.', 'deyim', 'agzi-kulaklarina-varmak'),
  ('ağzından bal damlamak', 'Çok tatlı ve gönül alıcı konuşmak.', 'Öyle güzel konuşuyor ki ağzından bal damlıyor.', 'deyim', 'agzindan-bal-damlamak'),
  ('ağzına geleni söylemek', 'Düşünmeden, kırıcı biçimde konuşmak.', 'Sinirlenince ağzına geleni söyledi.', 'deyim', 'agzina-geleni-soylemek'),
  ('ağzını bıçak açmamak', 'Hiç konuşmamak.', 'Bütün gün ağzını bıçak açmadı.', 'deyim', 'agzini-bicak-acmamak'),
  ('ayağını yorganına göre uzatmak', 'Gelirine göre harcama yapmak.', 'Bütçeni korumak için ayağını yorganına göre uzat.', 'deyim', 'ayagini-yorganina-gore-uzatmak'),
  ('ayağına dolanmak', 'İşi yaparken engel olmak ya da hata yaptırmak.', 'Heyecan cümlelerini ayağına doladı.', 'deyim', 'ayagina-dolanmak'),
  ('ayağa kalkmak', 'Karşı çıkmak ya da tepki göstermek.', 'Karardan sonra herkes ayağa kalktı.', 'deyim', 'ayaga-kalkmak'),
  ('ayak bağı olmak', 'Birinin işini yavaşlatmak, engel olmak.', 'Sürekli soru sorarak ayak bağı olma.', 'deyim', 'ayak-bagi-olmak'),
  ('başını derde sokmak', 'Kendine sorun açmak.', 'Düşünmeden attığı mesaj başını derde soktu.', 'deyim', 'basini-derde-sokmak'),
  ('başından savmak', 'Birini ilgilenmeden göndermek.', 'Soruyu başından savdı.', 'deyim', 'basindan-savmak'),
  ('başının çaresine bakmak', 'Kendi işini kendi çözmek.', 'Ben gelene kadar başının çaresine bak.', 'deyim', 'basinin-caresine-bakmak'),
  ('başı göğe ermek', 'Çok mutlu olmak.', 'Kazanınca başı göğe erdi.', 'deyim', 'basi-goge-ermek'),
  ('baş tacı etmek', 'Çok değer vermek.', 'Misafirleri baş tacı ettiler.', 'deyim', 'bas-taci-etmek'),
  ('başa çıkmak', 'Bir zorluğu yönetebilmek.', 'Bu tempoyla tek başına başa çıkmak zor.', 'deyim', 'basa-cikmak'),
  ('bel bağlamak', 'Güvenmek, umut bağlamak.', 'Tek bir sonuca bel bağlama.', 'deyim', 'bel-baglamak'),
  ('beline kuvvet', 'Yapılan işe teşekkür veya takdir bildiren söz.', 'Taşımaya yardım ettin, beline kuvvet.', 'deyim', 'beline-kuvvet'),
  ('benzi atmak', 'Korku ya da heyecandan rengi değişmek.', 'Sonucu görünce benzi attı.', 'deyim', 'benzi-atmak'),
  ('bıyık altından gülmek', 'Gizlice alay eder gibi gülmek.', 'Söylediklerine bıyık altından güldü.', 'deyim', 'biyik-altindan-gulmek'),
  ('bir baltaya sap olamamak', 'Hayatta belirli bir iş sahibi olamamak.', 'Ailesi onun bir baltaya sap olamamasından yakınıyor.', 'deyim', 'bir-baltaya-sap-olamamak'),
  ('bir deri bir kemik kalmak', 'Aşırı zayıflamak.', 'Hastalıktan sonra bir deri bir kemik kaldı.', 'deyim', 'bir-deri-bir-kemik-kalmak'),
  ('bir eli yağda bir eli balda olmak', 'Çok rahat şartlarda yaşamak.', 'Onun bir eli yağda bir eli balda.', 'deyim', 'bir-eli-yagda-bir-eli-balda-olmak'),
  ('bir kulağından girip öbüründen çıkmak', 'Söylenenin etkisiz kalması.', 'Uyarılar bir kulağından girip öbüründen çıkıyor.', 'deyim', 'bir-kulagindan-girip-oburunden-cikmak'),
  ('bir taşla iki kuş vurmak', 'Tek işte iki yarar sağlamak.', 'Toplantıyı erkene alıp bir taşla iki kuş vurdu.', 'deyim', 'bir-tasla-iki-kus-vurmak'),
  ('bıçak kemiğe dayanmak', 'Dayanma sınırına gelmek.', 'Artık bıçak kemiğe dayandı.', 'deyim', 'bicak-kemige-dayanmak'),
  ('boyun eğmek', 'İstemese de kabullenmek.', 'Baskıya boyun eğmedi.', 'deyim', 'boyun-egmek'),
  ('burnu büyük', 'Kendini beğenmiş.', 'Biraz burnu büyük davranıyor.', 'deyim', 'burnu-buyuk'),
  ('burnunun dikine gitmek', 'Kimseyi dinlemeden bildiğini yapmak.', 'Yine burnunun dikine gitti.', 'deyim', 'burnunun-dikine-gitmek'),
  ('can kulağıyla dinlemek', 'Çok dikkatli dinlemek.', 'Herkes onu can kulağıyla dinledi.', 'deyim', 'can-kulagiyla-dinlemek'),
  ('canı burnunda olmak', 'Çok sıkılmış ya da yorulmuş olmak.', 'Bu hafta canım burnumda.', 'deyim', 'cani-burnunda-olmak'),
  ('canını dişine takmak', 'Çok büyük çaba göstermek.', 'Projeyi yetiştirmek için canını dişine taktı.', 'deyim', 'canini-disine-takmak'),
  ('cebini doldurmak', 'Haksız kazanç elde etmek.', 'İşten çok cebini doldurmanın peşinde.', 'deyim', 'cebini-doldurmak'),
  ('ciğeri beş para etmemek', 'Hiç değeri olmamak.', 'Onun sözünün ciğeri beş para etmez.', 'deyim', 'cigeri-bes-para-etmemek'),
  ('devede kulak', 'Bütün içinde çok küçük bir parça.', 'Bu masraf, toplam bütçede devede kulak.', 'deyim', 'devede-kulak'),
  ('dil dökmek', 'İkna etmek için çok konuşmak.', 'Gelmesi için saatlerce dil döktü.', 'deyim', 'dil-dokmek'),
  ('dile düşmek', 'Hakkında çok konuşulmak.', 'Bir anda dile düştü.', 'deyim', 'dile-dusmek'),
  ('dilinde tüy bitmek', 'Aynı şeyi defalarca söylemekten yorulmak.', 'Söyle söyle dilimde tüy bitti.', 'deyim', 'dilinde-tuy-bitmek'),
  ('diş bilemek', 'Birine karşı kin beslemek.', 'Ona hâlâ diş biliyor.', 'deyim', 'dis-bilemek'),
  ('dört gözle beklemek', 'Büyük istekle beklemek.', 'Tatil gününü dört gözle bekliyorum.', 'deyim', 'dort-gozle-beklemek'),
  ('duman olmak', 'Bir anda ortadan kaybolmak.', 'Mesajı görünce duman oldu.', 'deyim', 'duman-olmak'),
  ('el ele vermek', 'Güç birliği yapmak.', 'Sorunu çözmek için el ele verdiler.', 'deyim', 'el-ele-vermek'),
  ('el etek çekmek', 'Bir işten tamamen uzaklaşmak.', 'Sosyal medyadan el etek çekti.', 'deyim', 'el-etek-cekmek'),
  ('el üstünde tutmak', 'Çok değer vermek.', 'Yeni geleni el üstünde tuttular.', 'deyim', 'el-ustunde-tutmak'),
  ('eli ayağına dolaşmak', 'Heyecanlanıp ne yapacağını şaşırmak.', 'Sahneye çıkınca eli ayağına dolaştı.', 'deyim', 'eli-ayagina-dolasmak'),
  ('eli açık', 'Cömert.', 'Eli açık biridir, paylaşmayı sever.', 'deyim', 'eli-acik'),
  ('eli dar', 'Maddi durumu sıkışık olmak.', 'Bu ay biraz eli dar.', 'deyim', 'eli-dar'),
  ('elinden düşürmemek', 'Bir şeyi sürekli kullanmak ya da yanında taşımak.', 'Telefonu elinden düşürmüyor.', 'deyim', 'elinden-dusurmemek'),
  ('eline yüzüne bulaştırmak', 'Bir işi becerememek.', 'Basit işi eline yüzüne bulaştırdı.', 'deyim', 'eline-yuzune-bulastirmak'),
  ('etekleri zil çalmak', 'Çok sevinmek.', 'Haberi duyunca etekleri zil çaldı.', 'deyim', 'etekleri-zil-calmak'),
  ('gaza gelmek', 'Birinin etkisiyle aşırı heveslenmek.', 'Yorumları görünce gaza geldi.', 'deyim', 'gaza-gelmek'),
  ('göz boyamak', 'Gerçeği gizleyip hoş göstermek.', 'Rapor biraz göz boyamak için hazırlanmış.', 'deyim', 'goz-boyamak'),
  ('gözden kaçmak', 'Dikkat edilmediği için fark edilmemek.', 'Detay gözden kaçmış.', 'deyim', 'gozden-kacmak'),
  ('göz doldurmak', 'Başarısı veya görünüşüyle etkilemek.', 'İlk sunumunda göz doldurdu.', 'deyim', 'goz-doldurmak'),
  ('göz kamaştırmak', 'Çok etkileyici olmak.', 'Yeni tasarım gerçekten göz kamaştırıyor.', 'deyim', 'goz-kamastirmak'),
  ('göz koymak', 'Sahip olmayı istemek.', 'O koltuğa göz koymuş.', 'deyim', 'goz-koymak'),
  ('gözü arkada kalmak', 'Bir şeyi geride bırakırken içinin rahat etmemesi.', 'Evden çıkarken gözü arkada kaldı.', 'deyim', 'gozu-arkada-kalmak'),
  ('gözü kara', 'Tehlikeyi düşünmeden cesur davranan.', 'Gözü kara bir kararla başladı.', 'deyim', 'gozu-kara'),
  ('gözüne girmek', 'Birinin takdirini kazanmak.', 'Patronun gözüne girmeye çalışıyor.', 'deyim', 'gozune-girmek'),
  ('gözüne uyku girmemek', 'Kaygıdan uyuyamamak.', 'Sınavdan önce gözüne uyku girmedi.', 'deyim', 'gozune-uyku-girmemek'),
  ('gün yüzü görmemek', 'Hiç kullanılmamak ya da fayda sağlamamak.', 'Aldığı defter gün yüzü görmedi.', 'deyim', 'gun-yuzu-gormemek'),
  ('hafife almak', 'Önemsememek.', 'Bu işi hafife alma.', 'deyim', 'hafife-almak'),
  ('haddini bilmek', 'Yerini ve sınırını bilmek.', 'Biraz haddini bilmeyi öğrenmeli.', 'deyim', 'haddini-bilmek'),
  ('harfi harfine', 'Tam olarak, eksiksiz biçimde.', 'Söylediğini harfi harfine yaptı.', 'deyim', 'harfi-harfine'),
  ('havada kalmak', 'Sonuçsuz kalmak.', 'Teklif havada kaldı.', 'deyim', 'havada-kalmak'),
  ('hayal kırıklığına uğramak', 'Umduğunu bulamamak.', 'Sonuçtan sonra hayal kırıklığına uğradı.', 'deyim', 'hayal-kirikligina-ugramak'),
  ('hesaba katmak', 'Bir olasılığı önceden düşünmek.', 'Bu gecikmeyi hesaba katmamıştık.', 'deyim', 'hesaba-katmak'),
  ('içine atmak', 'Üzüntüsünü belli etmemek.', 'Ne yaşadıysa içine attı.', 'deyim', 'icine-atmak'),
  ('içine doğmak', 'Sezmek.', 'Bir terslik olacağı içine doğmuş.', 'deyim', 'icine-dogmak'),
  ('içi içine sığmamak', 'Heyecan ve sevinçten yerinde duramamak.', 'Yola çıkmadan önce içi içine sığmıyordu.', 'deyim', 'ici-icine-sigmamak'),
  ('iki lafın belini kırmak', 'Kısa da olsa sohbet etmek.', 'Gel de iki lafın belini kıralım.', 'deyim', 'iki-lafin-belini-kirmak'),
  ('iş başa düşmek', 'Kimse yardım etmeyince işi kendisi yapmak zorunda kalmak.', 'İş başa düştü, oturup kendim yaptım.', 'deyim', 'is-basa-dusmek'),
  ('işin içinden çıkmak', 'Karışık bir durumu çözebilmek.', 'Bu hesabın içinden çıkamadım.', 'deyim', 'isin-icinden-cikmak'),
  ('işi yokuşa sürmek', 'Kolay işi zorlaştırmak.', 'Basit talebi yine yokuşa sürdü.', 'deyim', 'isi-yokusa-surmek'),
  ('kafa dinlemek', 'Sakinleşmek için gürültüden uzaklaşmak.', 'Hafta sonu biraz kafa dinlemek istiyorum.', 'deyim', 'kafa-dinlemek'),
  ('kafaya koymak', 'Bir şeyi kesin olarak yapmaya karar vermek.', 'Bu yıl taşınmayı kafaya koydu.', 'deyim', 'kafaya-koymak'),
  ('kalbini kırmak', 'Birini üzmek.', 'Şaka yapayım derken kalbini kırdı.', 'deyim', 'kalbini-kirmak'),
  ('kanat germek', 'Koruyup kollamak.', 'Yıllarca kardeşine kanat gerdi.', 'deyim', 'kanat-germek'),
  ('kanı kaynamak', 'Birini hemen sevip yakın hissetmek.', 'Yeni gelen çocuğa kanı kaynadı.', 'deyim', 'kani-kaynamak'),
  ('kapısını çalmak', 'Yardım veya destek istemek için birine gitmek.', 'İlk onun kapısını çaldı.', 'deyim', 'kapisini-calmak'),
  ('kara kara düşünmek', 'Kaygıyla düşünmek.', 'Bütün gece kara kara düşündü.', 'deyim', 'kara-kara-dusunmek'),
  ('karnı tok sırtı pek', 'Temel ihtiyaçları karşılanmış, hali vakti yerinde.', 'Karnı tok sırtı pek yaşayıp gidiyor.', 'deyim', 'karni-tok-sirti-pek'),
  ('kaş yapayım derken göz çıkarmak', 'İyilik yapmaya çalışırken zarar vermek.', 'Düzeltirken kaş yapayım derken göz çıkardı.', 'deyim', 'kas-yapayim-derken-goz-cikarmak'),
  ('kendine yedirememek', 'Bir şeyi gururuna uygun bulmayıp kabullenememek.', 'O sözü kendine yediremedi.', 'deyim', 'kendine-yedirememek'),
  ('kılı kırk yarmak', 'Aşırı titiz davranmak.', 'Detaylarda kılı kırk yarıyor.', 'deyim', 'kili-kirk-yarmak'),
  ('kıl payı', 'Çok az farkla.', 'Sınavı kıl payı kaçırdı.', 'deyim', 'kil-payi'),
  ('kimseye eyvallahı olmamak', 'Kimseye boyun eğmemek.', 'Kimseye eyvallahı olmayan biridir.', 'deyim', 'kimseye-eyvallahi-olmamak'),
  ('kök söktürmek', 'Çok zorlamak.', 'Hoca sınavda kök söktürdü.', 'deyim', 'kok-sokturmek'),
  ('kulak kabartmak', 'Gizlice ya da dikkatle dinlemek.', 'Yan masadaki konuşmaya kulak kabarttı.', 'deyim', 'kulak-kabartmak'),
  ('kulak tıkamak', 'Duymazdan gelmek.', 'Uyarılara kulak tıkadı.', 'deyim', 'kulak-tikamak'),
  ('küplere binmek', 'Çok öfkelenmek.', 'Yanıtı görünce küplere bindi.', 'deyim', 'kuplere-binmek'),
  ('laf taşımak', 'Birinin sözünü başkasına taşıyarak arayı bozmak.', 'Laf taşıyıp ortamı gerdi.', 'deyim', 'laf-tasimak'),
  ('lafa tutmak', 'Birini konuşmayla oyalamak.', 'Onu lafa tutup vakit kazandı.', 'deyim', 'lafa-tutmak'),
  ('lokmasını saymak', 'Birinin her harcamasını veya yediğini aşırı takip etmek.', 'İnsanların lokmasını saymayı bırak.', 'deyim', 'lokmasini-saymak'),
  ('meydan okumak', 'Açıkça karşı koymak.', 'Rakiplerine meydan okudu.', 'deyim', 'meydan-okumak'),
  ('nabız yoklamak', 'Karşı tarafın fikrini dolaylı yoldan anlamaya çalışmak.', 'Önce biraz nabız yokladı.', 'deyim', 'nabiz-yoklamak'),
  ('nal toplamak', 'Rakibinin çok gerisinde kalmak.', 'Yarışta diğerleri nal topladı.', 'deyim', 'nal-toplamak'),
  ('nefes aldırmamak', 'Hiç fırsat vermemek.', 'Rakibine nefes aldırmadı.', 'deyim', 'nefes-aldirmamak'),
  ('nokta atışı yapmak', 'Tam isabetli seçim veya tespit yapmak.', 'Önerisi tam nokta atışı oldu.', 'deyim', 'nokta-atisi-yapmak'),
  ('ortalığı ayağa kaldırmak', 'Büyük gürültü veya telaş çıkarmak.', 'Küçük mesele için ortalığı ayağa kaldırdı.', 'deyim', 'ortaligi-ayaga-kaldirmak'),
  ('ömrünü tüketmek', 'Bir iş veya kişi için çok emek ve zaman harcamak.', 'Bu proje için ömrünü tüketti.', 'deyim', 'omrunu-tuketmek'),
  ('pireyi deve yapmak', 'Küçük olayı büyütmek.', 'Her şeyi pireyi deve yapma.', 'deyim', 'pireyi-deve-yapmak'),
  ('saçını süpürge etmek', 'Birinin rahatı için çok emek vermek.', 'Çocukları için saçını süpürge etti.', 'deyim', 'sacini-supurge-etmek'),
  ('saman alevi gibi', 'Çabuk parlayıp hemen sönen.', 'Hevesi saman alevi gibi kaldı.', 'deyim', 'saman-alevi-gibi'),
  ('sırra kadem basmak', 'Aniden ortadan kaybolmak.', 'Mesajdan sonra sırra kadem bastı.', 'deyim', 'sirra-kadem-basmak'),
  ('sudan çıkmış balığa dönmek', 'Ne yapacağını bilemez duruma gelmek.', 'Yeni ofiste sudan çıkmış balığa döndü.', 'deyim', 'sudan-cikmis-baliga-donmek'),
  ('surat asmak', 'Kırgın veya öfkeli görünmek.', 'Sabah sabahtan surat asma.', 'deyim', 'surat-asmak'),
  ('şaka kaldırmamak', 'Şakadan hoşlanmamak.', 'Bu konuda şaka kaldırmıyor.', 'deyim', 'saka-kaldirmamak'),
  ('şartları zorlamak', 'Normalin ötesine geçmek.', 'Bu hedef için şartları zorluyoruz.', 'deyim', 'sartlari-zorlamak'),
  ('şimşekleri üstüne çekmek', 'Tepkileri üzerine toplamak.', 'O açıklamayla şimşekleri üstüne çekti.', 'deyim', 'simsekleri-ustune-cekmek'),
  ('tam üstüne basmak', 'Doğru noktayı bulmak.', 'Sorunun kaynağının tam üstüne bastın.', 'deyim', 'tam-ustune-basmak'),
  ('tadı tuzu kalmamak', 'Eskisi kadar keyif vermemek.', 'Bu işin artık tadı tuzu kalmadı.', 'deyim', 'tadi-tuzu-kalmamak'),
  ('taşıma suyla değirmen dönmemek', 'Geçici çözümlerle işin yürümemesi.', 'Taşıma suyla değirmen dönmez, kalıcı çözüm lazım.', 'deyim', 'tasima-suyla-degirmen-donmemek'),
  ('tek kalemde silmek', 'Birini veya bir şeyi tamamen gözden çıkarmak.', 'Onca emeği tek kalemde sildi.', 'deyim', 'tek-kalemde-silmek'),
  ('tepesine çıkmak', 'Birini çok şımartmak ya da baskı kurmak.', 'Bu kadar izin verirsen tepesine çıkar.', 'deyim', 'tepesine-cikmak'),
  ('ters köşe yapmak', 'Beklenmedik bir şekilde şaşırtmak.', 'Final herkesi ters köşe yaptı.', 'deyim', 'ters-kose-yapmak'),
  ('toz kondurmamak', 'Birine veya bir şeye kusur yakıştırmamak.', 'Takımına toz kondurmuyor.', 'deyim', 'toz-kondurmamak'),
  ('tüy dikmek', 'Kötü bir durumu daha da kötüleştirmek.', 'Son sözüyle iyice tüy dikti.', 'deyim', 'tuy-dikmek'),
  ('uçan kuştan haber vermek', 'Her şeyden haberdar olmak.', 'Ona gizli bir şey kalmaz, uçan kuştan haberi var.', 'deyim', 'ucan-kustan-haber-vermek'),
  ('üstüne düşmek', 'Bir işle çok ilgili şekilde ilgilenmek.', 'Bu konunun üstüne düşersen çözülür.', 'deyim', 'ustune-dusmek'),
  ('vakit kazanmak', 'Zaman elde etmek.', 'Toplantıyı erteleyip biraz vakit kazandı.', 'deyim', 'vakit-kazanmak'),
  ('yerden yere vurmak', 'Ağır şekilde eleştirmek.', 'Filmi sosyal medyada yerden yere vurdular.', 'deyim', 'yerden-yere-vurmak'),
  ('yola gelmek', 'İnat veya ters davranıştan vazgeçmek.', 'Bir süre sonra yola geldi.', 'deyim', 'yola-gelmek'),
  ('yüz vermek', 'Şımarmasına yol açacak kadar ilgi göstermek.', 'Çok yüz verme, işi suistimal ediyor.', 'deyim', 'yuz-vermek'),
  ('yüz yüze bakmak', 'Birlikte yaşam veya çalışma ilişkisini sürdürmek.', 'Yarın yine yüz yüze bakacağız.', 'deyim', 'yuz-yuze-bakmak'),
  ('zurnanın zırt dediği yer', 'İşin en kritik noktası.', 'Zurnanın zırt dediği yere geldik.', 'deyim', 'zurnanin-zirt-dedigi-yer')
on conflict (slug) do update
set
  kelime = excluded.kelime,
  anlam = excluded.anlam,
  ornek_cumle = excluded.ornek_cumle,
  kategori = excluded.kategori;
