insert into public.kelimeler
  (kelime, anlam, ornek_cumle, kategori, slug)
values
  ('rizz', 'Karşı cinsi etkileme yeteneği, çekicilik.', 'Adam''ın rizz''i var ya, herkesi etkiliyor.', 'argo', 'rizz'),
  ('sus payı', 'Birinin sırrını saklaması için verilen para veya iyilik.', 'Bana sus payı vermeye çalışma.', 'argo', 'sus-payi'),
  ('kral', 'Çok iyi, harika anlamında kullanılan onay ifadesi.', 'Kral iş çıkardın be.', 'argo', 'kral'),
  ('sallama', 'Yalan söylemek veya uydurma yapmak.', 'Sallıyorsun sen bunu.', 'argo', 'sallama'),
  ('efsane', 'Olağanüstü, muhteşem.', 'Efsane bir gece oldu.', 'argo', 'efsane'),
  ('toxic', 'Zehirli, zarar veren ilişki veya kişi.', 'Toxic biri bu, uzak dur.', 'argo', 'toxic'),
  ('red flag', 'Uyarı işareti, tehlike sinyali.', 'Bu kadar red flag varken nasıl devam edersin?', 'argo', 'red-flag'),
  ('green flag', 'Olumlu işaret, iyi özellik.', 'Dakik biri, green flag.', 'argo', 'green-flag'),
  ('vibe', 'Ortam, his, enerji.', 'Bu yerin vibi çok iyi.', 'argo', 'vibe'),
  ('cringe', 'Utanç verici, ikinci el utanç hissettiren.', 'Çok cringe bir durum.', 'argo', 'cringe'),
  ('lowkey', 'Sessiz sedasız, az bilinen.', 'Lowkey çok güzel bir yer.', 'argo', 'lowkey'),
  ('highkey', 'Açıkça, belirgin şekilde.', 'Highkey haklısın.', 'argo', 'highkey'),
  ('flex', 'Sahip olduğu şeyle övünmek.', 'Arabasıyla flex yapıyor.', 'argo', 'flex'),
  ('cap', 'Yalan söylemek.', 'No cap, gerçekten öyle.', 'argo', 'cap'),
  ('no cap', 'Yalan yok, gerçekten.', 'No cap en iyi filmdi.', 'argo', 'no-cap'),
  ('slay', 'Harika görünmek veya bir şeyi mükemmel yapmak.', 'Bugün slaydin ya.', 'argo', 'slay'),
  ('stan', 'Birinin aşırı hayranı olmak.', 'BTS''i stanlayanlar burada mı?', 'argo', 'stan'),
  ('ship', 'İki kişiyi birbirine yakıştırmak.', 'Bu ikiliye çok ship yapıyorum.', 'argo', 'ship'),
  ('glow up', 'Fiziksel veya kişisel gelişim.', 'Glow up yapmış ya.', 'argo', 'glow-up'),
  ('era', 'Bir dönem veya hal.', 'Şu an çalışma eramındayım.', 'argo', 'era'),
  ('npc', 'Hayatta pasif kalan, kendi kararı olmayan kişi.', 'NPC gibi yaşıyor.', 'argo', 'npc'),
  ('goat', 'En iyi, efsane.', 'GOAT tartışılmaz.', 'argo', 'goat'),
  ('mid', 'Vasat, ortalama.', 'Film çok middi.', 'argo', 'mid'),
  ('ratio', 'Yanıta verilen beğeni yorumu geçmek.', 'Ratio yedi.', 'argo', 'ratio'),
  ('ghostlamak', 'Biri ile iletişimi aniden kesmek.', 'Ghostladı mı seni?', 'argo', 'ghostlamak'),
  ('situationship', 'Resmi olmayan ilişki.', 'Situationship içinde sıkışmış.', 'argo', 'situationship'),
  ('ick', 'Birinde aniden iğrenme hissi.', 'Ick geldi geçti.', 'argo', 'ick'),
  ('fomo', 'Bir şeyi kaçırma korkusu.', 'Fomo yaşıyorum.', 'argo', 'fomo'),
  ('delulu', 'Gerçekçi olmayan hayaller kurmak.', 'Biraz delulu ama seviyorum.', 'argo', 'delulu'),
  ('manifestlemek', 'Bir şeyin olmasını istemek ve inanmak.', 'Manifeste et bunu.', 'argo', 'manifestlemek'),
  ('villain arc', 'Kötü adam dönemine girmek.', 'Villain arcım başladı.', 'argo', 'villain-arc'),
  ('Roman empire', 'Sürekli düşünülen şey.', 'Benim Roman Empire''m bu.', 'argo', 'roman-empire'),
  ('iconic', 'Unutulmaz, simgesel.', 'Çok iconic bir an.', 'argo', 'iconic'),
  ('aesthetic', 'Estetik bir his veya görünüm.', 'Aesthetic bir yer.', 'argo', 'aesthetic'),
  ('bestie', 'En yakın arkadaş.', 'Bestiem geldi.', 'argo', 'bestie'),
  ('valid', 'Geçerli, anlaşılır.', 'Valid bir sebep.', 'argo', 'valid'),
  ('core memory', 'Önemli anı.', 'Core memory oldu bu.', 'argo', 'core-memory'),
  ('cancel', 'Birini toplum dışı bırakmak.', 'Cancel edildi.', 'argo', 'cancel'),
  ('clout', 'Popülerlik, etki.', 'Clout için yapıyor.', 'argo', 'clout'),
  ('unhinged', 'Dengesiz, kontrolsüz.', 'Unhinged davranış.', 'argo', 'unhinged')
on conflict (slug) do update
set
  kelime = excluded.kelime,
  anlam = excluded.anlam,
  ornek_cumle = excluded.ornek_cumle,
  kategori = excluded.kategori;
